import { AnyCurrency } from '~/types'

export const TRANSACTION_DEPOSIT_COMISSION: Record<AnyCurrency, number> = {
  XTR: 10,
  TON: 0.5,
}

export const TRANSACTION_DEPOSIT_COMISSION_NUMBER: Record<AnyCurrency, number> = {
  XTR: 0.1,
  TON: 0.005,
}

export const TRANSACTION_WITHDRAW_COMISSION = 15
export const TRANSACTION_WITHDRAW_COMISSION_NUMBER = 0.15
export const TRANSACTION_BOOKED_USERS_XTR_AMOUNT = 150
export const TRANSACTION_SANTA_GAME_XTR_UNSTOPPED_AMOUNT = 150
export const TRANSACTION_SANTA_GAME_XTR_STOPPED_AMOUNT = 50
export const TRANSACTION_NEW_USER_XTR_AMOUNT = 2
export const TRANSACTION_NEW_USER_REFFERER_XTR_AMOUNT = 5
export const TRANSACTION_USER_REFFERER_XTR_COMISSION = 2
