export const TRANSACTION_DEPOSIT_COMISSION = 10
export const TRANSACTION_DEPOSIT_COMISSION_NUMBER = 0.1
export const TRANSACTION_WITHDRAW_COMISSION = 15
export const TRANSACTION_WITHDRAW_COMISSION_NUMBER = 0.15
export const TRANSACTION_BOOKED_USERS_XTR_AMOUNT = 150
