export const ROUTE = {
  home: '/',
  userWishList: '/user/:id',
  about: '/about',
  wishNew: '/new',
  wish: '/wish/:id',
  unavailable: '/unavailable',
  favorites: '/favorites',
  games: '/games',
  game: '/games/:type',
  gameById: '/game/:id',
  subscribeRoot: '/favorites/:id',
  settings: '/settings',
  categorySettings: '/settings/category',
  categoryNew: '/category/new',
  category: '/category/:id',
}
